/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import javax.swing.JOptionPane;

/**
 * Clase que representa la pantalla principal.
 *
 * @author Equipo 3
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Constructor que inicializa los componentes del formulario.
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuCastings = new javax.swing.JMenu();
        menuCastingsRegistrarCasting = new javax.swing.JMenuItem();
        menuCastingsRegistrarPerfil = new javax.swing.JMenuItem();
        menuCastingsBuscarCasting = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuClienteRegistrar = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuOpcionesAcercaDe = new javax.swing.JMenuItem();
        menuOpcionesSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Castings");

        menuCastings.setMnemonic('f');
        menuCastings.setText("Menú Castings");

        menuCastingsRegistrarCasting.setMnemonic('o');
        menuCastingsRegistrarCasting.setText("Registrar Casting");
        menuCastingsRegistrarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCastingsRegistrarCastingActionPerformed(evt);
            }
        });
        menuCastings.add(menuCastingsRegistrarCasting);

        menuCastingsRegistrarPerfil.setMnemonic('s');
        menuCastingsRegistrarPerfil.setText("Registrar Perfil");
        menuCastingsRegistrarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCastingsRegistrarPerfilActionPerformed(evt);
            }
        });
        menuCastings.add(menuCastingsRegistrarPerfil);

        menuCastingsBuscarCasting.setMnemonic('o');
        menuCastingsBuscarCasting.setText("Buscar Casting");
        menuCastingsBuscarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCastingsBuscarCastingActionPerformed(evt);
            }
        });
        menuCastings.add(menuCastingsBuscarCasting);

        menuBar.add(menuCastings);

        menuCliente.setMnemonic('e');
        menuCliente.setText("Menú Cliente");

        menuClienteRegistrar.setMnemonic('t');
        menuClienteRegistrar.setText("Registrar");
        menuClienteRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteRegistrarActionPerformed(evt);
            }
        });
        menuCliente.add(menuClienteRegistrar);

        menuBar.add(menuCliente);

        menuOpciones.setMnemonic('e');
        menuOpciones.setText("Opciones");
        menuOpciones.setToolTipText("");

        menuOpcionesAcercaDe.setMnemonic('t');
        menuOpcionesAcercaDe.setText("Acerca De");
        menuOpcionesAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesAcercaDeActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesAcercaDe);

        menuOpcionesSalir.setMnemonic('t');
        menuOpcionesSalir.setText("Salir");
        menuOpcionesSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesSalir);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Función para abrir el formulario de cliente.
     * @param evt evento al que escucha.
     */
    private void menuClienteRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteRegistrarActionPerformed
        FrmCliente frmCliente= FrmCliente.obtenerFrmCliente();
        frmCliente.mostrarFormulario();
    }//GEN-LAST:event_menuClienteRegistrarActionPerformed
    /**
     * Función para abrir la opción acerca de.
     * @param evt evento al que escucha.
     */
    private void menuOpcionesAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this, "Alex Gael García Acosta - 00000228721 \nJuan Pablo Sotelo Verdugo - 00000229391"
                + "\nCarlos Arturo Valle Encinas - 00000228219", "Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuOpcionesAcercaDeActionPerformed
    /**
     * Función para cerrar la pantalla.
     * @param evt evento al que escucha.
     */
    private void menuOpcionesSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuOpcionesSalirActionPerformed
    /**
     * Función para abrir el formulario de perfiles.
     * @param evt evento al que escucha.
     */
    private void menuCastingsRegistrarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCastingsRegistrarPerfilActionPerformed
        FrmPerfil frmPerfil= FrmPerfil.obtenerFrmPerfil();
        frmPerfil.mostrarFormulario();
    }//GEN-LAST:event_menuCastingsRegistrarPerfilActionPerformed
    /**
     * Función para abrir el formulario de castings.
     * @param evt evento al que escucha.
     */
    private void menuCastingsRegistrarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCastingsRegistrarCastingActionPerformed
        FrmCasting frmCasting= FrmCasting.obtenerFrmCasting();
        frmCasting.mostrarFormulario();
    }//GEN-LAST:event_menuCastingsRegistrarCastingActionPerformed
    /**
     * Función para abrir el formulario de busqueda.
     * @param evt evento al que escucha.
     */
    private void menuCastingsBuscarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCastingsBuscarCastingActionPerformed
        FrmBusqueda frmBusqueda= FrmBusqueda.obtenerFrmBusqueda();
        frmBusqueda.mostrarFormulario();
    }//GEN-LAST:event_menuCastingsBuscarCastingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCastings;
    private javax.swing.JMenuItem menuCastingsBuscarCasting;
    private javax.swing.JMenuItem menuCastingsRegistrarCasting;
    private javax.swing.JMenuItem menuCastingsRegistrarPerfil;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuClienteRegistrar;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuOpcionesAcercaDe;
    private javax.swing.JMenuItem menuOpcionesSalir;
    // End of variables declaration//GEN-END:variables

}
